name: build and deploy
on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    name: Build and Release (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile with PyInstaller
        run: pyinstaller compile.spec

      - name: Release
        run: |
          gh release create ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} -t ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} 'dist/BloonsFarmUI'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build_windows:
    name: Build and Release (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile with PyInstaller
        run: pyinstaller compile.spec

      - name: Release
        run: |
          gh release edit ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} -m ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} -a dist/BloonsFarmUI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build_macos:
    name: Build and Release (MacOS)
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile with PyInstaller
        run: pyinstaller compile.spec

      - name: Release
        run: |
          # Rename the mac executable so it doesn't share a name with the linux executable
          mv dist/BloonsFarmUI dist/BloonsFarmUi_macOS
          gh release edit ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} -m ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} -a dist/BloonsFarmUi_macOS
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
